version: "3"
services:
  affix-frontend-production:
    #platform: linux/x86_64
    image: affix-frontend-production:${ENV}
    # build: ./affix-frontend/
    restart: unless-stopped
    ports: 
      - "80:80"
      # - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-app

  strapi-backend:
    image: strapi-backend
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: affix
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      APP_KEYS : ak0BCrt+kki4HR4WcCoCJQ==,tN3a8kB8X4jBeGgzwkOWXA==,5y2H1Qb+mUlgqevFZp2fBA==,20A4t7yoDz6Z2eIlix/9oA==
      JWT_SECRET : e753ef1f-84b7-4a95-bf11-5839127abd0b
      API_TOKEN_SALT : 63a75fafe45c1baa8f8544b453e1a03c
      CLOUDINARY_NAME : carisoven
      CLOUDINARY_KEY: 874225613597632
      CLOUDINARY_SECRET : 8Hdw98ZLE_UBYjN_LaPLWr-41vQ
    env_file:
      - ./affix-backend/.env.dev
    restart: unless-stopped
    volumes:
      - ./affix-backend:/usr/srv/app
      - /usr/srv/app/node_modules
    ports:
      - '1337:1337'
    networks:
      - mern-app
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: affix
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    # env_file:
    #   - ./affix-backend/.env.dev
    networks:
      - mern-app


networks:
  mern-app:
    driver: bridge
volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local