version: '3'
services:
  affix-frontend:
    image: affix-frontend
    build: ./affix-frontend/
    stdin_open: true
    ports: 
          - "3000:3000"
    volumes:
      - ./affix-frontend/:/usr/srv/app
      - /usr/srv/app/node_modules
    networks:
      - mern-app
      
  strapi-backend:
    image: strapi-backend
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
      APP_KEYS : ${APP_KEYS}
      JWT_SECRET : ${JWT_SECRET}
      API_TOKEN_SALT : ${API_TOKEN_SALT}
      CLOUDINARY_NAME : ${CLOUDINARY_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET : ${CLOUDINARY_SECRET}
    restart: unless-stopped
    env_file:
      - ./affix-backend/.env.dev
    volumes:
      - ./affix-backend:/usr/srv/app
      - /usr/srv/app/node_modules
    ports:
      - '1337:1337'
    networks:
      - mern-app
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - ./affix-backend/.env.dev
    networks:
      - mern-app
  

networks:
  mern-app:
    driver: bridge
volumes:
  data:
    driver: local