version: "3"
services:
  affix-frontend-production:
    #platform: linux/x86_64
    image: affix-frontend-production
    # build: ./affix-frontend/
    restart: unless-stopped
    ports: 
      - "80:3000"
      # - "443:443"
    # volumes:
    #   - caddy-data:/data
    #   - caddy-config:/config
#     networks:
#       - mern-app

# networks:
#   mern-app:
#     driver: bridge
volumes:
  data:
    driver: local
  # caddy-data:
  #   driver: local
  # caddy-config:
  #   driver: local