
export const USER_LOADED = "USER_LOADED";
export const USER_LOADFAIL = "USER_LOADFAIL";
export const CLEAR_USER = "CLEAR_USER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT = "LOGOUT";

//Login With Google Suceessful and Fail
export const LOGINSIGNUP_CALLBACK_ERROR="LOGINSIGNUP_CALLBACK_ERROR";
export const LOGINSIGNUP_CALLBACK="LOGINSIGNUP_CALLBACK";